### PR TITLE
PSQL and autom po file message generation support

### PR DESCRIPTION
**Pull request by cwirz**

### CODE REVIEW

**Comment by Visgean** [comment]
This is going to break sqlite support imho.

**Comment by cwirz** [comment]
@Visgean Ok i will implement db detection for this
Any advice how to do this?

**Comment by cisarpavel** [comment]
Using '1' should be fully valid for both pgsql and sqlite. I don't see any need to change it. Is there any problem with it?

**Comment by cwirz** [comment]
yes i got an error
`ProgrammingError: operator does not exist: integer = boolean`

**Comment by Visgean** [comment]
I have looked at django db backend code and there does not seem to be any 'boolean value' definition... :/ So I think the best way / simplest is to dictionary with what each backend uses: 

```
{
   "sqlite3": "1",
   "postgresql": "TRUE",
}
```

or something like that and then format the query specifically to the backend. 

https://stackoverflow.com/questions/18846174/django-detect-database-backend

**Comment by cisarpavel** [comment]
@Wirzi can you post here what version of django and postgresql do you use?

**Comment by cwirz** [comment]
@cisarpavel 
$ psql -V
$ psql (PostgreSQL) 9.4.0

**Comment by michalkaspar** [comment]
I finally solved it with using '1' and successfully tested it with sqlite3 version 2.6.0 and Postgresql version 9.4.0.

**Pull request closed without merging**
